### ISSUE TITLE
Error in Launch Synchronization

### ISSUE THREAD

**Issue by zhavir** [JayVora-SerpentCS/SerpentCS_Contributions#1]
When I try to launch Synchronization on a scenario similar to https://www.youtube.com/watch?v=8FzP6aC3NaU I get an error: 'res.request' doesn't exist when they try to create new record on this table(/wizard/base_synchro.py row 250)

I'm use:
Centos 7
Postgesql 9.4
Odoo 8.0 lastest

**Comment by ShrutiVerma31** [comment]
The error has been corrected. You can get the base_synchro module from here -
https://github.com/ShrutiVerma31/SerpentCS_Contributions-v8

**Comment by ShrutiVerma31** [comment]
The error has been fixed. You can get the base_synchro module here -
https://github.com/ShrutiVerma31/SerpentCS_Contributions-v8/

**Comment by jacksolutions** [comment]
i am using odoov8, i have created new database with demo data loaded which i am going to sync to empty database. first i tried to sync the partners and it worked flawlessly but then i tried to sync lead and it gave me below error, can you please suggest what am i doing wrong?



Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/addons/base_synchro/wizard/base_synchro.py", line 272, in upload_download_multi_thread
    threaded_synchronization = threading.Thread(target=self.upload_download())
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/custom/addons/base_synchro/wizard/base_synchro.py", line 236, in upload_download
    self.synchronize(server, obj_rec)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/custom/addons/base_synchro/wizard/base_synchro.py", line 128, in synchronize
    pool_dest.get(object.model_id.model).write(self._cr, self.user_id.id, [id2], value)
  File "/opt/odoo/custom/addons/base_synchro/wizard/base_synchro.py", line 44, in <lambda>
    return lambda cr, uid, *args, **kwargs: self.rpc.execute(self.server.server_db, self.uid, self.server.password, self.ressource, name, *args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
Fault: <Fault warning -- Integrity Error

The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: login - login]: ''>

**Comment by jacksolutions** [comment]
[object with reference: login - login]: ''>

**Comment by jacksolutions** [comment]
"object with reference: login - login]: ''

**Comment by jacksolutions** [comment]
it seems like it broke with the above error but behind the scene it was syncing, so i tried 2,3 times same steps so now it has created duplicate leads, so same leads are appearing 2,3 times, so how to avoid duplication?

**Comment by jacksolutions** [comment]
but still opportunities didnt sync, i selected lead/opportunity while syncing, so something is still wrong.. 

thank you for the great plugin.. you guys are doing a good job!

**Comment by jacksolutions** [comment]
okay so leads are syncing fine, it is the opportunities that are throwing the errors i reported. 

Thanks

**Comment by JayVora-SerpentCS** [comment]
@jacksolutions Thanks for the report!
We shall check and revert at the earliest possible.

**Comment by JayVora-SerpentCS** [comment]
Closing the issue for now, as we have migrated to v9 n v10. Let us know if this happens again.
