### ISSUE TITLE
O12CE Install error: psycopg2.ProgrammingError: ON CONFLICT DO UPDATE 

### ISSUE THREAD

**Issue by davidgonzalezb** [JayVora-SerpentCS/SerpentCS_Contributions#363]
Hello
I have error install
Odoo 12 community, Ubuntu 18.04 Server, AWS Amazon

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-61>", line 2, in button_immediate_install
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 444, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 552, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/modules/loading.py", line 231, in load_module_graph
    module.with_context(overwrite=overwrite)._update_translations()
  File "/opt/odoo/odoo/addons/base/models/ir_module.py", line 876, in _update_translations
    self.env['ir.translation'].load_module_terms(mod_names, filter_lang)
  File "/opt/odoo/odoo/addons/base/models/ir_translation.py", line 778, in load_module_terms
    tools.trans_load(self._cr, trans_file, lang, verbose=False, module_name=module_name, context=context)
  File "/opt/odoo/odoo/tools/translate.py", line 1011, in trans_load
    result = trans_load_data(cr, fileobj, fileformat, lang, verbose=verbose, module_name=module_name, context=context)
  File "/opt/odoo/odoo/tools/translate.py", line 1155, in trans_load_data
    irt_cursor.finish()
  File "/opt/odoo/odoo/addons/base/models/ir_translation.py", line 156, in finish
    """ % (self._model_table, self._table))
  File "/opt/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.

**Comment by JayVora-SerpentCS** [comment]
Which module are we talking about?
Thanks.

**Comment by davidgonzalezb** [comment]
Hello
Is this: Multi-DB Synchronization by Odoo S.A., Serpent Consulting Services Pvt. Ltd.

**Comment by JayVora-SerpentCS** [comment]
@Swapnesh-serpentcs please check

**Comment by Swapnesh-SerpentCS** [comment]
I tested this in the morning and Installation was successful on 12 CE.
However, I am working on Fixing a few things (As we did for v11 in the last week).

Hopefully, this will fix the issue and we can check again if there is something to do specifically.

**Comment by davidgonzalezb** [comment]
Hello. I was testing the App. the problem is the Language "Spanish (MX)" for Mexico in Odoo. Thanks

**Comment by JayVora-SerpentCS** [comment]
@Swapnesh-SerpentCS do read on https://apps.odoo.com/apps/modules/12.0/base_synchro/

Thanks.

**Comment by JayVora-SerpentCS** [comment]
@davidgonzalezb Can you please pull the latest source and update ?

**Comment by davidgonzalezb** [comment]
Hello. We've already updated the app. We download from the following Links: https://apps.odoo.com/apps/modules/12.0/base_synchro/ and https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/tree/12.0/label
We have the same problem

Where is the latest source??

Thanks


 File "/opt/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
